version: '2'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/zhoujiabao/php:nginx1.20.0
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
  php:
    image: registry.cn-hangzhou.aliyuncs.com/zhoujiabao/php:php8.1.0
    ports:
      - "9001:9000"        
    volumes:
            - ./www:/www
  database:
    image: registry.cn-hangzhou.aliyuncs.com/zhoujiabao/php:mysql5.7
    ports:
      - "3307:3306"
    environment:
          - "MYSQL_ROOT_PASSWORD=root"
          - "MYSQL_DATABASE=larabbs"
          - "MYSQL_USER=homestead"
          - "MYSQL_PASSWORD=secret"    

  redis:
        image: registry.cn-hangzhou.aliyuncs.com/zhoujiabao/php:redis5
        ports:
            - 6380:6379
      