version: '2'
services:
  nginx:
    image: nginx1.20.0
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    ports:
      - "9001:9000"        
    volumes:
            - ./www:/www
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
          - "MYSQL_ROOT_PASSWORD=root"
          - "MYSQL_DATABASE=larabbs"
          - "MYSQL_USER=homestead"
          - "MYSQL_PASSWORD=secret"    

  redis:
        image: redis:5
        ports:
            - 6380:6379
      